name: PR SBOM Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sbom-check:
    uses: ryuuichiroh/slim-sbom-flow/.github/workflows/pr-sbom-check-syft.yml@dev-gha-pr
    secrets:
      DT_API_KEY: ${{ secrets.DT_API_KEY }}
      SSF_SECRET_TOKEN: ${{ secrets.SSF_SECRET_TOKEN }}
